/* ============================================================
   Strophoid — “Paradox Engine” (Gallery Script)
   ParameterControls-integrated

   ------------------------------------------------------------
   EMBEDDED TEXT (PRESERVED VERBATIM AS REQUESTED)
   ------------------------------------------------------------
   Let’s crack open the strophoid, Barry—not just as a curve, but as a conceptual lever. You called it a “paradox engine,” and I think that’s exactly the right instinct. It’s a curve born from tension: symmetry and asymmetry, inversion and reflection, fixed points and moving lines. Let’s make it inspectable.
   ---
   🧩 What is a Strophoid?
   At its core, the strophoid is a locus of points generated by a geometric construction involving:
   • A pole point `\( O \)`
   • A fixed point `\( A \)`
   • A curve `\( C \)` (often a line)
   • A variable line `\( L \)` through `\( O \)`, intersecting `\( C \)` at point `\( K \)`

   From there:
   • You find two points `\( P_1 \)` and `\( P_2 \)` on line `\( L \)` such that their distance from `\( K \)` equals the distance from `\( A \)` to `\( K \)`:

   KP_1 = KP_2 = AK
   - The **locus of `\( P_1 \)` and `\( P_2 \)`** as `\( L \)` rotates around `\( O \)` is the strophoid [A]
   This construction creates a curve with:
   - A **node** (double point) at `\( O \)`
   - **Orthogonal tangents** at the node
   - Often **two branches**—one looping inward, one flaring outward
   ---
   ### 🔧 Manipulating It: Parametric Form
   If you want to render or manipulate it programmatically, here’s a parametric form when `\( C \)` is a line and `\( A = (a, 0) \)`, `\( O = (0, 0) \)`:
   ```js
   function strophoid(t, a = 1) {
   const x = a * Math.tan(t);
   const y = a * Math.tan(t) * Math.sin(t);
   return { x, y };
   }

   This version gives you the right strophoid, also known as the logocyclic curve. It’s singular at the origin, with branches that diverge dramatically.
   ---
   🌀 Why It’s a Paradox Engine
   The strophoid thrives on contradiction:
   • It’s symmetric, yet its branches behave wildly differently.
   • It’s defined by distance, yet produces asymptotic behavior.
   • It has a node, but also infinite extension.

   You could use it as:
   • A symbolic object in your sketchpad to explore inversion, reflection, and locus generation.
   • A test case for parametric vs. symbolic rendering.
   • A UI metaphor: sliders that control paradoxical tension (e.g., pole angle vs. fixed point distance).

   ---
   🧠 Next Steps
   Want to build a `Strophoid` module with:
   • Parametric generator
   • Symbolic metadata (e.g., node, asymptotes, branches)
   • UI controls for pole/fixed point manipulation
   • Overlay showing construction steps?

   We could scaffold it as a paradox explorer—something that teaches as it renders. Let me know how deep you want to go.

   Perfect — let’s treat the Strophoid as a standalone module for now, something you can explore, manipulate, and reflect on without needing to integrate it into the full sketchpad system just yet. This gives you space to understand its behavior, test its geometry, and decide how it might evolve into a symbolic or paradoxical object later.
   ---
   🧩 Standalone Strophoid Module — Conceptual Scaffold
   🔹 Purpose
   To explore the strophoid as a geometric and symbolic object:
   • Parametric rendering
   • Symbolic metadata
   • Visual overlays (optional)
   • Configurable parameters

   ---
   🧱 Suggested Structure
   strophoid/
   ├── strophoid.js          # Parametric evaluator + metadata
   ├── strophoid.test.js     # Basic geometry tests
   ├── strophoid.html        # Canvas + UI controls
   ├── strophoid.css         # Optional styling

   ---
   🔧 Core Function (strophoid.js)
   export function strophoidParametric(t, a = 100) {
     const denom = 1 + t * t;
     return {
       x: a * (1 - t * t) / denom,
       y: a * (2 * t) / denom
     };
   }
   export const strophoidMetadata = {
     name: 'Right Strophoid',
     equation: 'x²(a - x) = a y²',
     tags: ['cubic', 'node', 'paradox'],
     description: 'A curve with a double point at the origin, symmetric yet divergent.'
   };

   ---
   🧪 Minimal Test (strophoid.test.js)
   import { strophoidParametric } from './strophoid.js';
   function testPointCount() {
     const pts = [];
     for (let t = -10; t <= 10; t += 0.1) {
       pts.push(strophoidParametric(t));
     }
     console.assert(pts.length > 0, 'Should generate points');
   }
   testPointCount();

   ---
   🖼️ Simple Viewer (strophoid.html)
   <canvas id="strophoidCanvas" width="800" height="600"></canvas>
   <button onclick="toggleDiscussion()">Show Discussion</button>
   <div id="discussion" class="hidden">
     <p>The strophoid is a paradoxical curve with a node at the origin...</p>
   </div>
   <script type="module" src="./strophoid.js"></script>

   ---
   🧠 Why This Matters
   • You get a clean space to explore the curve’s behavior.
   • You can prototype overlays or symbolic annotations without system dependencies.
   • You’ll build confidence and clarity before integrating it into your sketchpad.

   ---
   Would you like help drafting the canvas rendering loop or symbolic overlay for this standalone module next time? We can keep it lightweight and inspectable.

   ------------------------------------------------------------
   GALLERY SCRIPT NOTES
   ------------------------------------------------------------
   - This script uses the explicit parametric form included above:
       x = a * tan(t)
       y = a * tan(t) * sin(t)
   - Because tan(t) has vertical asymptotes, the parameter range must
     stay away from odd multiples of π/2.
   - This version renders as CURVE-STITCH:
       two point sequences on the strophoid are generated, then
       stitch lines are drawn between paired indices.
   - No local ctx variable is declared in this file.
   - No ctx is passed into helper functions.
   - Controls are OBJECT-KEYED (no "key" fields); controls use "widget".
============================================================ */

import { buildParameterControls } from "/ui/parameterControls.js";

/* ============================================================
   scriptInfo
============================================================ */
export const scriptInfo = {

  title: "Strophoid — Curve Stitch",

  params: {

    /* Curve scale */
    a: 160,

    /* Parameter range (degrees), must avoid +/- 90, 270, ... */
    tMinDeg: -75,
    tMaxDeg:  75,

    /* Sampling */
    steps: 1500,

    /* Stitching */
    stitchEvery: 2,          /* draw every Nth stitch (1 = all) */
    stitchOffset: 0,         /* offset pairing index (can be negative) */

    /* Rendering */
    stitchWidth: 1,
    stitchColor: "#000000",

    /* Optional overlays */
    showAxes: true,
    axisWidth: 1,
    axisColor: "#888888",

    showNode: true,
    nodeRadius: 4,
    nodeColor: "#cc0000",

    /* Optional: also draw the curve outline for reference */
    showOutline: false,
    outlineWidth: 1,
    outlineColor: "#cc0000"

  },

  /* Alias for compatibility with existing scriptRunner expectations. */
  parameters: null,

  /* Controls are OBJECT-KEYED. */
  controls: {

    a: {
      label: "a (scale)",
      widget: "range",
      min: 20,
      max: 400,
      step: 1
    },

    tMinDeg: {
      label: "t min (deg)",
      widget: "range",
      min: -89,
      max: 0,
      step: 1
    },

    tMaxDeg: {
      label: "t max (deg)",
      widget: "range",
      min: 0,
      max: 89,
      step: 1
    },

    steps: {
      label: "Steps",
      widget: "range",
      min: 300,
      max: 8000,
      step: 50
    },

    stitchEvery: {
      label: "Stitch every",
      widget: "range",
      min: 1,
      max: 20,
      step: 1
    },

    stitchOffset: {
      label: "Stitch offset",
      widget: "range",
      min: -1000,
      max: 1000,
      step: 1
    },

    stitchWidth: {
      label: "Stitch width",
      widget: "range",
      min: 1,
      max: 8,
      step: 1
    },

    stitchColor: {
      label: "Stitch color",
      widget: "color"
    },

    showAxes: {
      label: "Show axes",
      widget: "checkbox"
    },

    axisWidth: {
      label: "Axis width",
      widget: "range",
      min: 1,
      max: 6,
      step: 1
    },

    axisColor: {
      label: "Axis color",
      widget: "color"
    },

    showNode: {
      label: "Show node (origin)",
      widget: "checkbox"
    },

    nodeRadius: {
      label: "Node radius",
      widget: "range",
      min: 1,
      max: 16,
      step: 1
    },

    nodeColor: {
      label: "Node color",
      widget: "color"
    },

    showOutline: {
      label: "Show outline",
      widget: "checkbox"
    },

    outlineWidth: {
      label: "Outline width",
      widget: "range",
      min: 1,
      max: 8,
      step: 1
    },

    outlineColor: {
      label: "Outline color",
      widget: "color"
    }

  },

  /* Elements cache (drawRegistry-style). */
  elements: null,

  /* Compatibility no-op. */
  onParamChange() {
    /* Intentionally empty. */
  }, // end onParamChange

  /* Redraw handler is set during runPattern(). */
  redrawHandler: null

}; // end scriptInfo


/* ============================================================
   Math helpers
============================================================ */
function toRadians(deg) {
  return (deg * Math.PI) / 180;
} // end toRadians


/* ============================================================
   Strophoid parametric: t -> {x,y}
   Uses the explicit form from the embedded text:

     x = a * tan(t)
     y = a * tan(t) * sin(t)

============================================================ */
function strophoidPointAt(t, p) {

  const tanT = Math.tan(t);

  return {
    x: p.a * tanT,
    y: p.a * tanT * Math.sin(t)
  };

} // end strophoidPointAt


/* ============================================================
   Sampling
============================================================ */
function generatePoints(p) {

  const pts = [];

  const steps = p.steps;

  const tMin = toRadians(p.tMinDeg);
  const tMax = toRadians(p.tMaxDeg);

  for (let i = 0; i < steps; i++) {

    const t = tMin + ((tMax - tMin) * i) / (steps - 1);
    const pt = strophoidPointAt(t, p);

    pts.push({ x: pt.x, y: pt.y, t: t });

  }

  return pts;

} // end generatePoints


/* ============================================================
   Canvas helpers
============================================================ */
function clearCanvas() {

  ctx.setTransform(1, 0, 0, 1, 0, 0);
  ctx.clearRect(0, 0, ctx.canvas.width, ctx.canvas.height);

} // end clearCanvas


function beginWorldTransform() {

  const w = ctx.canvas.width;
  const h = ctx.canvas.height;

  /* World coords:
     - origin at canvas center
     - +y is up (so we flip y) */
  ctx.setTransform(1, 0, 0, 1, 0, 0);
  ctx.translate(w / 2, h / 2);
  ctx.scale(1, -1);

} // end beginWorldTransform


function drawAxes(p) {

  const w = ctx.canvas.width;
  const h = ctx.canvas.height;

  const xMin = -w / 2;
  const xMax =  w / 2;
  const yMin = -h / 2;
  const yMax =  h / 2;

  ctx.save();

  ctx.lineWidth = p.axisWidth;
  ctx.strokeStyle = p.axisColor;

  ctx.beginPath();

  /* x-axis */
  ctx.moveTo(xMin, 0);
  ctx.lineTo(xMax, 0);

  /* y-axis */
  ctx.moveTo(0, yMin);
  ctx.lineTo(0, yMax);

  ctx.stroke();

  ctx.restore();

} // end drawAxes


function drawNode(p) {

  ctx.save();

  ctx.fillStyle = p.nodeColor;

  ctx.beginPath();
  ctx.arc(0, 0, p.nodeRadius, 0, Math.PI * 2);
  ctx.fill();

  ctx.restore();

} // end drawNode


function drawOutline(points, p) {

  ctx.save();

  ctx.lineWidth = p.outlineWidth;
  ctx.strokeStyle = p.outlineColor;

  ctx.beginPath();
  ctx.moveTo(points[0].x, points[0].y);

  for (let i = 1; i < points.length; i++) {
    ctx.lineTo(points[i].x, points[i].y);
  }

  ctx.stroke();

  ctx.restore();

} // end drawOutline


/* ============================================================
   Curve-stitch rendering

   We build two sequences:
     A[i] = points[i]
     B[i] = points[rev(i)] where rev(i) = (N-1-i) + offset  (wrapped)

   Then draw stitch lines from A[i] to B[i], skipping by stitchEvery.

============================================================ */
function drawStitches(points, p) {

  const n = points.length;

  ctx.save();

  ctx.lineWidth = p.stitchWidth;
  ctx.strokeStyle = p.stitchColor;

  ctx.beginPath();

  for (let i = 0; i < n; i += p.stitchEvery) {

    let j = (n - 1 - i) + p.stitchOffset;

    /* Wrap j into [0, n-1]. */
    j = j % n;
    if (j < 0) j += n;

    ctx.moveTo(points[i].x, points[i].y);
    ctx.lineTo(points[j].x, points[j].y);

  }

  ctx.stroke();
  ctx.restore();

} // end drawStitches


/* ============================================================
   Update / Draw lifecycle (drawRegistry-style)
============================================================ */
function init(p) {

  scriptInfo.elements = {
    element: {
      points: []
    }
  };

} // end init


function update(p) {

  scriptInfo.elements.element.points = generatePoints(p);

} // end update


function draw(p) {

  clearCanvas();

  beginWorldTransform();

  if (p.showAxes) {
    drawAxes(p);
  }

  drawStitches(scriptInfo.elements.element.points, p);

  if (p.showOutline) {
    drawOutline(scriptInfo.elements.element.points, p);
  }

  if (p.showNode) {
    drawNode(p);
  }

} // end draw


/* ============================================================
   runPattern (Gallery script entry point)
============================================================ */
export function runPattern() {

  /* ParameterControls expects this alias for many scripts. */
  scriptInfo.parameters = scriptInfo.params;

  /* Build UI controls into the Gallery Scripts tab area. */
  buildParameterControls(scriptInfo, "tab-scripts", true);

  /* Install redraw handler using the standard pattern you requested. */
  scriptInfo.redrawHandler = function () {

    update(scriptInfo.params);
    draw(scriptInfo.params);

  }; // end redrawHandler

  /* Cold start. */
  init(scriptInfo.params);
  scriptInfo.redrawHandler();

} // end runPattern
