/* controls/scripts/harmonographSandbox.js
   ============================================================
   HARMONOGRAPH SANDBOX (2-PENDULUM LATERAL)
   ============================================================
   Formula:
   x = A1 * sin(f1 * t + p1) * exp(-d1 * t)
   y = A2 * sin(f2 * t + p2) * exp(-d2 * t)
   ============================================================ */
   /* controls/scripts/harmonographSandbox.js
   ============================================================
   HARMONOGRAPH SANDBOX (2-PENDULUM LATERAL)
   ============================================================
   This script simulates a lateral harmonograph, a mechanical
   apparatus that uses pendulums to drive a pen. The resulting
   curves—Harmonograms—are the visual representation of
   superimposed oscillations decaying over time.

   MATHEMATICS:
   The drawing is generated by two independent decaying sine
   waves for the X and Y axes:
   x(t) = A * sin(f1 * t + p1) * e^(-d1 * t)
   y(t) = A * sin(f2 * t + p2) * e^(-d2 * t)

   CONTROL GUIDE:
   ------------------------------------------------------------
   - Freq (f1, f2): Controls the "pitch" of each pendulum.
     Small differences (e.g., 2.0 vs 2.01) create the "beating"
     effect that makes the curve slowly rotate or shift.
   - Phase (p1, p2): Determines the starting position of the
     oscillation. Changing the relative phase between X and Y
     rotates the orientation of the shape.
   - Damping (d1, d2): Simulates friction and energy loss.
     0 = infinite loop (Lissajous figure).
     Higher values = curve spirals inward toward the center.
   - Duration: The total "swing time." Increase this to see
     the curve fill in more detail as it decays.
   - Step (Δt): Resolution. Lower values create smoother
     lines but require more processing power.
   ============================================================ */
import { Point } from "/classes/classes.js";
import { drawLine, printText, displayPoint } from "/draw/drawUtilities.js";
import { buildParameterControls } from "/ui/parameterControls.js";

export const scriptInfo = {
  title: "Harmonograph Sandbox",

  params: {
    f1: 2.0,
    p1: 0,
    d1: 0.01,
    f2: 2.01,
    p2: 1.57,
    d2: 0.01,
    duration: 100,
    step: 0.05,
    userScale: 150,
    color: "#8800ff",
    lineWidth: 1,
    showIntersections: false
  },

  controls: {
    f1: { widget: "range", label: "Freq X (f1)", min: 0.1, max: 10, step: 0.01 },
    p1: { widget: "range", label: "Phase X (p1)", min: 0, max: Math.PI * 2, step: 0.1 },
    d1: { widget: "range", label: "Damping X (d1)", min: 0, max: 0.1, step: 0.001 },
    f2: { widget: "range", label: "Freq Y (f2)", min: 0.1, max: 10, step: 0.01 },
    p2: { widget: "range", label: "Phase Y (p2)", min: 0, max: Math.PI * 2, step: 0.1 },
    d2: { widget: "range", label: "Damping Y (d2)", min: 0, max: 0.1, step: 0.001 },
    duration: { widget: "range", label: "Duration", min: 10, max: 1000, step: 10 },
    step: { widget: "range", label: "Step (Δt)", min: 0.001, max: 0.5, step: 0.001 },
    userScale: { widget: "range", label: "Scale", min: 50, max: 400, step: 10 },
    color: { widget: "colorPicker", label: "Stroke Color" },
    lineWidth: { widget: "range", label: "Line Width", min: 0.5, max: 5, step: 0.5 },
    showIntersections: { widget: "checkbox", label: "Show Intersections" }
  }
};

scriptInfo.parameters = scriptInfo.params;

/**
 * getLineIntersection(p1, p2, p3, p4)
 * Standard intersection check adapted from the core engine.
 */
function getLineIntersection(p1, p2, p3, p4) {
    const denom = (p4.y - p3.y) * (p2.x - p1.x) - (p4.x - p3.x) * (p2.y - p1.y);
    if (denom === 0) return null;

    const ua = ((p4.x - p3.x) * (p1.y - p3.y) - (p4.y - p3.y) * (p1.x - p3.x)) / denom;
    const ub = ((p2.x - p1.x) * (p1.y - p3.y) - (p2.y - p1.y) * (p1.x - p3.x)) / denom;

    const epsilon = 0.01;
    if (ua > epsilon && ua < (1 - epsilon) && ub > epsilon && ub < (1 - epsilon)) {
        return new Point(p1.x + ua * (p2.x - p1.x), p1.y + ua * (p2.y - p1.y));
    }
    return null;
}

/**
 * redrawHandler
 * Renders the decaying pendulum oscillations.
 */
scriptInfo.redrawHandler = function() {
  const p = scriptInfo.params;
  const f1 = parseFloat(p.f1);
  const p1 = parseFloat(p.p1);
  const d1 = parseFloat(p.d1);
  const f2 = parseFloat(p.f2);
  const p2 = parseFloat(p.p2);
  const d2 = parseFloat(p.d2);
  const scale = parseFloat(p.userScale);
  const dt = parseFloat(p.step);
  const tMax = parseFloat(p.duration);

  ctx.clearRect(0, 0, ctx.canvas.width, ctx.canvas.height);

  const cx = ctx.canvas.width / 2;
  const cy = ctx.canvas.height / 2;

  const segments = [];
  let prevPt = null;

  for (let t = 0; t <= tMax; t += dt) {
    // Decaying sine wave for X and Y
    const x = cx + (Math.sin(t * f1 + p1) * Math.exp(-d1 * t)) * scale;
    const y = cy + (Math.sin(t * f2 + p2) * Math.exp(-d2 * t)) * scale;
    const currPt = new Point(x, y);

    if (prevPt) {
      const newSeg = { p1: prevPt, p2: currPt };

      drawLine(newSeg.p1, newSeg.p2, p.color, p.lineWidth);

      if (p.showIntersections && segments.length > 2) {
        for (let j = 0; j < segments.length - 2; j++) {
          const old = segments[j];
          const hit = getLineIntersection(newSeg.p1, newSeg.p2, old.p1, old.p2);
          if (hit) displayPoint(hit, "red");
        }
      }
      segments.push(newSeg);
    }

    prevPt = currPt;
  }

  const labelText = `X: f=${f1} d=${d1} | Y: f=${f2} d=${d2}`;
  ctx.fillStyle = p.color;
  printText(labelText, new Point(10, 10));
};

export function runPattern() {
  buildParameterControls(scriptInfo, "tab-scripts", true);
  scriptInfo.redrawHandler();
}
